### PR TITLE
Make jdump an installable joomla package with automatic jdump plugin …

### PR DESCRIPTION
**Pull request by gruz**
…publishing. So instead of installing the component, the plugin and then publishing the plugin you can just quickly install the package

### CODE REVIEW

**Comment by mathiasverraes** [comment]
Hey @gruz do you want to take over ownership of jdump? I haven't been involved in joomla for many years?

**Comment by gruz** [comment]
Hi. Though I regret I've been involved in Joomla for many years, because it doesn't bring any noticable money or any other profit for me, I cannot leave it due to my extensions and users. "We are responsible for those who are tamed". 

And thus I use jdump often despite of some doubts I can take it. At least if there is nobody else except me.

**Comment by mathiasverraes** [comment]
Thanks, you should have gotten an invite for push access.

**Comment by garstud** [comment]
Great and thank you @gruz and @mathiasverraes . I can only rejoice to see that this project continues to live. I use it almost every day. And I will continue to help as I can. Thank you for all ;)

**Comment by gruz** [comment]
@mathiasverraes 
Please give a hint how to make a release in a correct way. If I use the web-interface, then the source code is just zipped. It's not an installable package. What is the way to make releases with the installable archive? 

Thanks.

**Comment by mathiasverraes** [comment]
The readme has a section: https://github.com/mathiasverraes/jdump#download
You need to install phing and run it.
However, I have no idea if that still works and if the produced packages will still work with current versions of joomla. This has all been a very long time ago for me.

Suggestions:

- try phing and see if you can get it to work
- inspect the old packages and see what they are supposed to look like
- inspect the build.xml file, which is the script phing uses
- find joomla docs about making packages
- create a new (bash or other) script to replace the phing script

**Comment by mathiasverraes** [comment]
oh and:

- update the readme me any information about building packages that can help future contributors

**Comment by gruz** [comment]
@mathiasverraes It's not a problem to build the package after the git is cloned. I want to make the git release with the installable package. Because if I just add a release using the git interface, it just zips the source code. Ok. I'll try to find an answer myself.

**Comment by mathiasverraes** [comment]
When you make a new release
https://github.com/mathiasverraes/jdump/releases/new , there's the option
to attach a binary. Just upload the installable package there?

**Comment by gruz** [comment]
Thanks. Didn't mention it (-:

**Pull request merged**
